/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class usbinterfacejava_UsbInterfaceJava */

#ifndef _Included_usbinterfacejava_UsbInterfaceJava
#define _Included_usbinterfacejava_UsbInterfaceJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     usbinterfacejava_UsbInterfaceJava
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
    
JNIEXPORT jstring JNICALL Java_usbinterfacejava_UsbInterfaceJava_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     usbinterfacejava_UsbInterfaceJava
 * Method:    SerialPort
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_usbinterfacejava_UsbInterfaceJava_SerialPort
  (JNIEnv *, jobject, jstring);

/*
 * Class:     usbinterfacejava_UsbInterfaceJava
 * Method:    isconnected
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_usbinterfacejava_UsbInterfaceJava_isconnected
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
