/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class usbinterfacejava_UsbInterfaceJava */

#ifndef _Included_usbinterfacejava_UsbInterfaceJava
#define _Included_usbinterfacejava_UsbInterfaceJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     usbinterfacejava_UsbInterfaceJava
 * Method:    Suma
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_usbinterfacejava_UsbInterfaceJava_Suma
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     usbinterfacejava_UsbInterfaceJava
 * Method:    Resta
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_usbinterfacejava_UsbInterfaceJava_Resta
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     usbinterfacejava_UsbInterfaceJava
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_usbinterfacejava_UsbInterfaceJava_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
