/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class usbinterfacejava_UsbInterfaceJava */

#ifndef _Included_usbinterfacejava_UsbInterfaceJava
#define _Included_usbinterfacejava_UsbInterfaceJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     usbinterfacejava_UsbInterfaceJava
 * Method:    SerialPort
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_usbinterfacejava_UsbInterfaceJava_SerialPort
  (JNIEnv *, jobject, jstring);

/*
 * Class:     usbinterfacejava_UsbInterfaceJava
 * Method:    isconnected
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_usbinterfacejava_UsbInterfaceJava_isconnected
  (JNIEnv *, jobject);

/*
 * Class:     usbinterfacejava_UsbInterfaceJava
 * Method:    readSerialPort
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_usbinterfacejava_UsbInterfaceJava_readSerialPort
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     usbinterfacejava_UsbInterfaceJava
 * Method:    writeSerialPort
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_usbinterfacejava_UsbInterfaceJava_writeSerialPort
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
